import = [
	"~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

opacity = 1.0

[font]
size = 12
normal = {family = "MesloLGS Nerd Font Mono", style = "Regular"}
